<a href="https://www.kaggle.com/code/kennethnjuguna/analyzing-a-real-world-data-set-with-sql-and-pytho?scriptVersionId=146793621" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Connect to the database
Let us first load the SQL extension and establish a connection with the database

The syntax for connecting to magic sql using sqllite is
%sql sqlite://DatabaseName

where DatabaseName will be your .db file

In [ ]:
%load_ext sql

In [ ]:
import csv, sqlite3

con = sqlite3.connect("socioeconomic.db")
cur = con.cursor()
!pip install pandas

In [ ]:
%sql sqlite:///socioeconomic.db

# <h2>Store the dataset in a Table</h2>
<p>In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. To analyze the data using SQL, it first needs to be stored in the database.</p>
<p>We will first read the csv files from the given url into pandas dataframes</p>
<p>Next we will be using the df.to_sql() function to convert each csv file to a table in sqlite with the csv data loaded in it.</p>

In [ ]:
import pandas
df = pandas.read_csv('https://data.cityofchicago.org/resource/jcxq-k9xf.csv')
df.to_sql("chicago_socioeconomic_data", con, if_exists='replace', index=False,method="multi")

You can verify that the table creation was successful by making a basic query like:

In [ ]:
%sql SELECT * FROM chicago_socioeconomic_data limit 5;

Find out how many rows we have in the dataset.

In [ ]:
%sql SELECT COUNT(*) FROM chicago_socioeconomic_data;

community areas in Chicago have a hardship index greater than 50.0

In [ ]:

%sql SELECT COUNT(*) FROM chicago_socioeconomic_data WHERE hardship_index > 50.0;

Maximum value of hardship index in this dataset

In [ ]:
%sql SELECT MAX(hardship_index) FROM chicago_socioeconomic_data;

C%sql SELECT community_area_name FROM chicago_socioeconomic_data where hardship_index=98.0ommunity area which has the highest hardship index

In [ ]:
%sql SELECT community_area_name FROM chicago_socioeconomic_data where hardship_index=98.0

Chicago community areas have per-capita incomes greater than $60,000

In [ ]:
%sql SELECT community_area_name FROM chicago_socioeconomic_data WHERE per_capita_income_ > 60000;

Create a scatter plot using the variables `per_capita_income_` and `hardship_index`. Explain the correlation between the two variables.

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

income_vs_hardship = %sql SELECT per_capita_income_, hardship_index FROM chicago_socioeconomic_data;
plot = sns.jointplot(x='per_capita_income_',y='hardship_index', data=income_vs_hardship.DataFrame())